### ISSUE TITLE
may be a typing error in make-handler-bind-case-without-no-error-case

### ISSUE THREAD

**Issue by hxzrx** [dbmcclain/Lisp-Actors#1]
in the function make-handler-bind-case-without-no-error-case in useful-macros/handlers.lisp

the 3rd line: (flet ((make-hander-binding (case) 
may be (flet ((make-handler-binding (case)

**Comment by dbmcclain** [comment]
Ah, yes! HANDLER, not HANDER… Thank you very much!

- DM

**Comment by hxzrx** [comment]
Sure!
